// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/e2engine/core/repository (interfaces: EntityRepository,ResourceRepository,TestRepository,TestExecutionRepository,TestSuiteExecutionRepository)
//
// Generated by this command:
//
//	mockgen-darwin-arm64-v0.6.0 -destination=mock/Repository.go -package=mock github.com/e2engine/core/repository EntityRepository,ResourceRepository,TestRepository,TestExecutionRepository,TestSuiteExecutionRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	repository "github.com/e2engine/core/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockEntityRepository is a mock of EntityRepository interface.
type MockEntityRepository[E repository.Entity] struct {
	ctrl     *gomock.Controller
	recorder *MockEntityRepositoryMockRecorder[E]
	isgomock struct{}
}

// MockEntityRepositoryMockRecorder is the mock recorder for MockEntityRepository.
type MockEntityRepositoryMockRecorder[E repository.Entity] struct {
	mock *MockEntityRepository[E]
}

// NewMockEntityRepository creates a new mock instance.
func NewMockEntityRepository[E repository.Entity](ctrl *gomock.Controller) *MockEntityRepository[E] {
	mock := &MockEntityRepository[E]{ctrl: ctrl}
	mock.recorder = &MockEntityRepositoryMockRecorder[E]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntityRepository[E]) EXPECT() *MockEntityRepositoryMockRecorder[E] {
	return m.recorder
}

// Create mocks base method.
func (m *MockEntityRepository[E]) Create(ctx context.Context, params *E) (*E, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*E)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEntityRepositoryMockRecorder[E]) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEntityRepository[E])(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockEntityRepository[E]) Delete(ctx context.Context, id string) (*E, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*E)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockEntityRepositoryMockRecorder[E]) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEntityRepository[E])(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockEntityRepository[E]) Get(ctx context.Context, id string) (*E, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*E)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEntityRepositoryMockRecorder[E]) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEntityRepository[E])(nil).Get), ctx, id)
}

// GetIDsByID mocks base method.
func (m *MockEntityRepository[E]) GetIDsByID(ctx context.Context, id string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDsByID", ctx, id)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDsByID indicates an expected call of GetIDsByID.
func (mr *MockEntityRepositoryMockRecorder[E]) GetIDsByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDsByID", reflect.TypeOf((*MockEntityRepository[E])(nil).GetIDsByID), ctx, id)
}

// List mocks base method.
func (m *MockEntityRepository[E]) List(ctx context.Context, params *repository.ListParams) ([]E, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]E)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEntityRepositoryMockRecorder[E]) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEntityRepository[E])(nil).List), ctx, params)
}

// MockResourceRepository is a mock of ResourceRepository interface.
type MockResourceRepository[E repository.ResourceEntity] struct {
	ctrl     *gomock.Controller
	recorder *MockResourceRepositoryMockRecorder[E]
	isgomock struct{}
}

// MockResourceRepositoryMockRecorder is the mock recorder for MockResourceRepository.
type MockResourceRepositoryMockRecorder[E repository.ResourceEntity] struct {
	mock *MockResourceRepository[E]
}

// NewMockResourceRepository creates a new mock instance.
func NewMockResourceRepository[E repository.ResourceEntity](ctrl *gomock.Controller) *MockResourceRepository[E] {
	mock := &MockResourceRepository[E]{ctrl: ctrl}
	mock.recorder = &MockResourceRepositoryMockRecorder[E]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceRepository[E]) EXPECT() *MockResourceRepositoryMockRecorder[E] {
	return m.recorder
}

// Create mocks base method.
func (m *MockResourceRepository[E]) Create(ctx context.Context, params *E) (*E, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*E)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockResourceRepositoryMockRecorder[E]) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockResourceRepository[E])(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockResourceRepository[E]) Delete(ctx context.Context, id string) (*E, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*E)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockResourceRepositoryMockRecorder[E]) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockResourceRepository[E])(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockResourceRepository[E]) Get(ctx context.Context, id string) (*E, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*E)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockResourceRepositoryMockRecorder[E]) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockResourceRepository[E])(nil).Get), ctx, id)
}

// GetIDsByID mocks base method.
func (m *MockResourceRepository[E]) GetIDsByID(ctx context.Context, id string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDsByID", ctx, id)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDsByID indicates an expected call of GetIDsByID.
func (mr *MockResourceRepositoryMockRecorder[E]) GetIDsByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDsByID", reflect.TypeOf((*MockResourceRepository[E])(nil).GetIDsByID), ctx, id)
}

// GetIDsByName mocks base method.
func (m *MockResourceRepository[E]) GetIDsByName(ctx context.Context, name string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDsByName", ctx, name)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDsByName indicates an expected call of GetIDsByName.
func (mr *MockResourceRepositoryMockRecorder[E]) GetIDsByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDsByName", reflect.TypeOf((*MockResourceRepository[E])(nil).GetIDsByName), ctx, name)
}

// List mocks base method.
func (m *MockResourceRepository[E]) List(ctx context.Context, params *repository.ListParams) ([]E, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]E)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockResourceRepositoryMockRecorder[E]) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockResourceRepository[E])(nil).List), ctx, params)
}

// MockTestRepository is a mock of TestRepository interface.
type MockTestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTestRepositoryMockRecorder
	isgomock struct{}
}

// MockTestRepositoryMockRecorder is the mock recorder for MockTestRepository.
type MockTestRepositoryMockRecorder struct {
	mock *MockTestRepository
}

// NewMockTestRepository creates a new mock instance.
func NewMockTestRepository(ctrl *gomock.Controller) *MockTestRepository {
	mock := &MockTestRepository{ctrl: ctrl}
	mock.recorder = &MockTestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestRepository) EXPECT() *MockTestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTestRepository) Create(ctx context.Context, params *repository.Test) (*repository.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*repository.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTestRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTestRepository)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockTestRepository) Delete(ctx context.Context, id string) (*repository.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*repository.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTestRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTestRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockTestRepository) Get(ctx context.Context, id string) (*repository.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*repository.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTestRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTestRepository)(nil).Get), ctx, id)
}

// GetByTag mocks base method.
func (m *MockTestRepository) GetByTag(ctx context.Context, tag string) ([]repository.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTag", ctx, tag)
	ret0, _ := ret[0].([]repository.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTag indicates an expected call of GetByTag.
func (mr *MockTestRepositoryMockRecorder) GetByTag(ctx, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTag", reflect.TypeOf((*MockTestRepository)(nil).GetByTag), ctx, tag)
}

// GetIDsByID mocks base method.
func (m *MockTestRepository) GetIDsByID(ctx context.Context, id string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDsByID", ctx, id)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDsByID indicates an expected call of GetIDsByID.
func (mr *MockTestRepositoryMockRecorder) GetIDsByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDsByID", reflect.TypeOf((*MockTestRepository)(nil).GetIDsByID), ctx, id)
}

// GetIDsByName mocks base method.
func (m *MockTestRepository) GetIDsByName(ctx context.Context, name string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDsByName", ctx, name)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDsByName indicates an expected call of GetIDsByName.
func (mr *MockTestRepositoryMockRecorder) GetIDsByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDsByName", reflect.TypeOf((*MockTestRepository)(nil).GetIDsByName), ctx, name)
}

// List mocks base method.
func (m *MockTestRepository) List(ctx context.Context, params *repository.ListParams) ([]repository.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]repository.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTestRepositoryMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTestRepository)(nil).List), ctx, params)
}

// MockTestExecutionRepository is a mock of TestExecutionRepository interface.
type MockTestExecutionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTestExecutionRepositoryMockRecorder
	isgomock struct{}
}

// MockTestExecutionRepositoryMockRecorder is the mock recorder for MockTestExecutionRepository.
type MockTestExecutionRepositoryMockRecorder struct {
	mock *MockTestExecutionRepository
}

// NewMockTestExecutionRepository creates a new mock instance.
func NewMockTestExecutionRepository(ctrl *gomock.Controller) *MockTestExecutionRepository {
	mock := &MockTestExecutionRepository{ctrl: ctrl}
	mock.recorder = &MockTestExecutionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestExecutionRepository) EXPECT() *MockTestExecutionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTestExecutionRepository) Create(ctx context.Context, params *repository.TestExecution) (*repository.TestExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*repository.TestExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTestExecutionRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTestExecutionRepository)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockTestExecutionRepository) Delete(ctx context.Context, id string) (*repository.TestExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*repository.TestExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTestExecutionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTestExecutionRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockTestExecutionRepository) Get(ctx context.Context, id string) (*repository.TestExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*repository.TestExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTestExecutionRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTestExecutionRepository)(nil).Get), ctx, id)
}

// GetByTestSuiteExecutionID mocks base method.
func (m *MockTestExecutionRepository) GetByTestSuiteExecutionID(ctx context.Context, id string) ([]repository.TestExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTestSuiteExecutionID", ctx, id)
	ret0, _ := ret[0].([]repository.TestExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTestSuiteExecutionID indicates an expected call of GetByTestSuiteExecutionID.
func (mr *MockTestExecutionRepositoryMockRecorder) GetByTestSuiteExecutionID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTestSuiteExecutionID", reflect.TypeOf((*MockTestExecutionRepository)(nil).GetByTestSuiteExecutionID), ctx, id)
}

// GetIDsByID mocks base method.
func (m *MockTestExecutionRepository) GetIDsByID(ctx context.Context, id string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDsByID", ctx, id)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDsByID indicates an expected call of GetIDsByID.
func (mr *MockTestExecutionRepositoryMockRecorder) GetIDsByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDsByID", reflect.TypeOf((*MockTestExecutionRepository)(nil).GetIDsByID), ctx, id)
}

// GetStatus mocks base method.
func (m *MockTestExecutionRepository) GetStatus(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockTestExecutionRepositoryMockRecorder) GetStatus(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockTestExecutionRepository)(nil).GetStatus), ctx, id)
}

// List mocks base method.
func (m *MockTestExecutionRepository) List(ctx context.Context, params *repository.ListParams) ([]repository.TestExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]repository.TestExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTestExecutionRepositoryMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTestExecutionRepository)(nil).List), ctx, params)
}

// SetCompleted mocks base method.
func (m *MockTestExecutionRepository) SetCompleted(ctx context.Context, params *repository.SetCompletedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCompleted", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCompleted indicates an expected call of SetCompleted.
func (mr *MockTestExecutionRepositoryMockRecorder) SetCompleted(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCompleted", reflect.TypeOf((*MockTestExecutionRepository)(nil).SetCompleted), ctx, params)
}

// SetRunning mocks base method.
func (m *MockTestExecutionRepository) SetRunning(ctx context.Context, params *repository.SetRunningParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRunning", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRunning indicates an expected call of SetRunning.
func (mr *MockTestExecutionRepositoryMockRecorder) SetRunning(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRunning", reflect.TypeOf((*MockTestExecutionRepository)(nil).SetRunning), ctx, params)
}

// MockTestSuiteExecutionRepository is a mock of TestSuiteExecutionRepository interface.
type MockTestSuiteExecutionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTestSuiteExecutionRepositoryMockRecorder
	isgomock struct{}
}

// MockTestSuiteExecutionRepositoryMockRecorder is the mock recorder for MockTestSuiteExecutionRepository.
type MockTestSuiteExecutionRepositoryMockRecorder struct {
	mock *MockTestSuiteExecutionRepository
}

// NewMockTestSuiteExecutionRepository creates a new mock instance.
func NewMockTestSuiteExecutionRepository(ctrl *gomock.Controller) *MockTestSuiteExecutionRepository {
	mock := &MockTestSuiteExecutionRepository{ctrl: ctrl}
	mock.recorder = &MockTestSuiteExecutionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestSuiteExecutionRepository) EXPECT() *MockTestSuiteExecutionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTestSuiteExecutionRepository) Create(ctx context.Context, params *repository.TestSuiteExecution) (*repository.TestSuiteExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*repository.TestSuiteExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTestSuiteExecutionRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTestSuiteExecutionRepository)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockTestSuiteExecutionRepository) Delete(ctx context.Context, id string) (*repository.TestSuiteExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*repository.TestSuiteExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTestSuiteExecutionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTestSuiteExecutionRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockTestSuiteExecutionRepository) Get(ctx context.Context, id string) (*repository.TestSuiteExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*repository.TestSuiteExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTestSuiteExecutionRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTestSuiteExecutionRepository)(nil).Get), ctx, id)
}

// GetIDsByID mocks base method.
func (m *MockTestSuiteExecutionRepository) GetIDsByID(ctx context.Context, id string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDsByID", ctx, id)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDsByID indicates an expected call of GetIDsByID.
func (mr *MockTestSuiteExecutionRepositoryMockRecorder) GetIDsByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDsByID", reflect.TypeOf((*MockTestSuiteExecutionRepository)(nil).GetIDsByID), ctx, id)
}

// GetStatus mocks base method.
func (m *MockTestSuiteExecutionRepository) GetStatus(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockTestSuiteExecutionRepositoryMockRecorder) GetStatus(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockTestSuiteExecutionRepository)(nil).GetStatus), ctx, id)
}

// List mocks base method.
func (m *MockTestSuiteExecutionRepository) List(ctx context.Context, params *repository.ListParams) ([]repository.TestSuiteExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]repository.TestSuiteExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTestSuiteExecutionRepositoryMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTestSuiteExecutionRepository)(nil).List), ctx, params)
}

// SetCompleted mocks base method.
func (m *MockTestSuiteExecutionRepository) SetCompleted(ctx context.Context, params *repository.SetCompletedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCompleted", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCompleted indicates an expected call of SetCompleted.
func (mr *MockTestSuiteExecutionRepositoryMockRecorder) SetCompleted(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCompleted", reflect.TypeOf((*MockTestSuiteExecutionRepository)(nil).SetCompleted), ctx, params)
}

// SetRunning mocks base method.
func (m *MockTestSuiteExecutionRepository) SetRunning(ctx context.Context, params *repository.SetRunningParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRunning", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRunning indicates an expected call of SetRunning.
func (mr *MockTestSuiteExecutionRepositoryMockRecorder) SetRunning(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRunning", reflect.TypeOf((*MockTestSuiteExecutionRepository)(nil).SetRunning), ctx, params)
}
