// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/e2engine/core/execute/runtime (interfaces: Service,ServiceProvider,Router,RouterProvider)
//
// Generated by this command:
//
//	mockgen-darwin-arm64-v0.6.0 -destination=mock/Runtime.go -package=mock github.com/e2engine/core/execute/runtime Service,ServiceProvider,Router,RouterProvider
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	call "github.com/e2engine/core/execute/call"
	runtime "github.com/e2engine/core/execute/runtime"
	grpc "github.com/e2engine/core/execute/runtime/service/grpc"
	model "github.com/e2engine/core/model"
	log "github.com/e2engine/core/pkg/log"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetRuntimeAddress mocks base method.
func (m *MockService) GetRuntimeAddress() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRuntimeAddress")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRuntimeAddress indicates an expected call of GetRuntimeAddress.
func (mr *MockServiceMockRecorder) GetRuntimeAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRuntimeAddress", reflect.TypeOf((*MockService)(nil).GetRuntimeAddress))
}

// Mount mocks base method.
func (m *MockService) Mount(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mount", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mount indicates an expected call of Mount.
func (mr *MockServiceMockRecorder) Mount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mount", reflect.TypeOf((*MockService)(nil).Mount), ctx)
}

// Unmount mocks base method.
func (m *MockService) Unmount(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmount", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmount indicates an expected call of Unmount.
func (mr *MockServiceMockRecorder) Unmount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmount", reflect.TypeOf((*MockService)(nil).Unmount), ctx)
}

// MockServiceProvider is a mock of ServiceProvider interface.
type MockServiceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockServiceProviderMockRecorder
	isgomock struct{}
}

// MockServiceProviderMockRecorder is the mock recorder for MockServiceProvider.
type MockServiceProviderMockRecorder struct {
	mock *MockServiceProvider
}

// NewMockServiceProvider creates a new mock instance.
func NewMockServiceProvider(ctrl *gomock.Controller) *MockServiceProvider {
	mock := &MockServiceProvider{ctrl: ctrl}
	mock.recorder = &MockServiceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceProvider) EXPECT() *MockServiceProviderMockRecorder {
	return m.recorder
}

// GetGRPCMethodResolver mocks base method.
func (m *MockServiceProvider) GetGRPCMethodResolver() grpc.MethodResolver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGRPCMethodResolver")
	ret0, _ := ret[0].(grpc.MethodResolver)
	return ret0
}

// GetGRPCMethodResolver indicates an expected call of GetGRPCMethodResolver.
func (mr *MockServiceProviderMockRecorder) GetGRPCMethodResolver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGRPCMethodResolver", reflect.TypeOf((*MockServiceProvider)(nil).GetGRPCMethodResolver))
}

// GetService mocks base method.
func (m *MockServiceProvider) GetService(spec *model.ServiceSpec) (runtime.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService", spec)
	ret0, _ := ret[0].(runtime.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetService indicates an expected call of GetService.
func (mr *MockServiceProviderMockRecorder) GetService(spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockServiceProvider)(nil).GetService), spec)
}

// MockRouter is a mock of Router interface.
type MockRouter struct {
	ctrl     *gomock.Controller
	recorder *MockRouterMockRecorder
	isgomock struct{}
}

// MockRouterMockRecorder is the mock recorder for MockRouter.
type MockRouterMockRecorder struct {
	mock *MockRouter
}

// NewMockRouter creates a new mock instance.
func NewMockRouter(ctrl *gomock.Controller) *MockRouter {
	mock := &MockRouter{ctrl: ctrl}
	mock.recorder = &MockRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouter) EXPECT() *MockRouterMockRecorder {
	return m.recorder
}

// Mount mocks base method.
func (m *MockRouter) Mount(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mount", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mount indicates an expected call of Mount.
func (mr *MockRouterMockRecorder) Mount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mount", reflect.TypeOf((*MockRouter)(nil).Mount), ctx)
}

// Register mocks base method.
func (m *MockRouter) Register(route *runtime.Route) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", route)
}

// Register indicates an expected call of Register.
func (mr *MockRouterMockRecorder) Register(route any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockRouter)(nil).Register), route)
}

// Unmount mocks base method.
func (m *MockRouter) Unmount(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmount", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmount indicates an expected call of Unmount.
func (mr *MockRouterMockRecorder) Unmount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmount", reflect.TypeOf((*MockRouter)(nil).Unmount), ctx)
}

// MockRouterProvider is a mock of RouterProvider interface.
type MockRouterProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRouterProviderMockRecorder
	isgomock struct{}
}

// MockRouterProviderMockRecorder is the mock recorder for MockRouterProvider.
type MockRouterProviderMockRecorder struct {
	mock *MockRouterProvider
}

// NewMockRouterProvider creates a new mock instance.
func NewMockRouterProvider(ctrl *gomock.Controller) *MockRouterProvider {
	mock := &MockRouterProvider{ctrl: ctrl}
	mock.recorder = &MockRouterProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouterProvider) EXPECT() *MockRouterProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRouterProvider) Get(logger log.Logger, recorder call.Recorder) runtime.Router {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", logger, recorder)
	ret0, _ := ret[0].(runtime.Router)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockRouterProviderMockRecorder) Get(logger, recorder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRouterProvider)(nil).Get), logger, recorder)
}
